# 1 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 2 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_MapScripts::
# 3 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.byte 0
# 4 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 5 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_EventScript_Man::
# 6 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
# 7 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	end
# 8 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 9 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_EventScript_Woman::
# 10 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
# 11 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	end
# 12 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 13 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_EventScript_NinjaBoy::
# 14 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
# 15 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	end
# 16 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 17 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
# 18 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Was braucht ein Trainer?\p"
# 19 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Kenntnis…\n"
# 20 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Strategie…\l"
# 21 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Ein glückliches Los…\l"
# 22 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Einen groben Überblick…\l"
# 23 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Seele…\l"
# 24 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Bravur…\l"
# 25 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Und eine gute Anlage…\p"
# 26 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Nun, das bringe ich alles mit!\n"
# 27 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Ich werde überall einfach unschlagbar\l"
# 28 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "sein!\p"
# 29 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Was? Pokémon?!\n"
# 30 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Was ist das denn? Kann man das essen?$"
# 31 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 32 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
# 33 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Hast du schon mal was über die\n"
# 34 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Kampfkoryphäen gehört?\p"
# 35 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "So nennt Scott die sieben Trainer,\n"
# 36 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "die die sieben Einrichtungen der\l"
# 37 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Kampfzone leiten.$"
# 38 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 39 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
# 40 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Im Duellturm hat mir ein älteres\n"
# 41 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Mädchen gesagt, dass ich sehr viel\l"
# 42 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Talent für's Kämpfen habe!\p"
# 43 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Ich mag aber lieber Pokémon-\n"
# 44 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Wettbewerbe!\p"
# 45 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Aber bei den Wettbewerben schneide\n"
# 46 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "ich nie so sonderlich gut ab.\p"
# 47 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Ob man auch für etwas Talent haben\n"
# 48 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "kann, obwohl man was anderes lieber\l"
# 49 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "mag?$"
