# 1 "data/maps/PacifidlogTown_House1/scripts.pory"

# 2 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_MapScripts::
# 3 "data/maps/PacifidlogTown_House1/scripts.pory"
	.byte 0
# 4 "data/maps/PacifidlogTown_House1/scripts.pory"

# 5 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_EventScript_Man::
# 6 "data/maps/PacifidlogTown_House1/scripts.pory"
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
# 7 "data/maps/PacifidlogTown_House1/scripts.pory"
	end
# 8 "data/maps/PacifidlogTown_House1/scripts.pory"

# 9 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_EventScript_Woman::
# 10 "data/maps/PacifidlogTown_House1/scripts.pory"
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
# 11 "data/maps/PacifidlogTown_House1/scripts.pory"
	end
# 12 "data/maps/PacifidlogTown_House1/scripts.pory"

# 13 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_Text_RegiStory:
# 14 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "In der Hoenn-Region gibt es drei\n"
# 15 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Pokémon, die die Stärke von Gestein,\l"
# 16 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Eis und Stahl repräsentieren.\p"
# 17 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Man sagt, sie verstecken sich in\n"
# 18 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Höhlen vor den Augen der Menschen.\p"
# 19 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Diese Geschichte wurde mir als Kind\n"
# 20 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "erzählt.$"
# 21 "data/maps/PacifidlogTown_House1/scripts.pory"

# 22 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
# 23 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "“Sechs Punkte öffnen drei Türen.”\p"
# 24 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Mein Großvater sagte das immer, aber\n"
# 25 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "ich habe keine Ahnung, was es bedeutet.$"
