MoveRelearner_Text_WouldLearnNewMoves:
	.string "Hallo, ich bin der Attacken-Lehrer.\n"
	.string "Möchtest du neue Attacken lernen?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Level-Up-Attacken$"

MoveRelearner_Text_EggMoves:
	.string "Ei-Attacken$"

MoveRelearner_Text_TMMoves:
	.string "TM-Attacken$"

MoveRelearner_Text_TutormoveMoves:
	.string "Attacken-Lehrer$"

MoveRelearner_Text_SeeYa:
	.string "Bis später!$"

MoveRelearner_Text_AnythingElse:
	.string "Kann ich sonst noch etwas für dich tun?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Bitte wähle ein Pokémon aus.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "Du hast keine Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Tut mir Leid…\n"
	.string "Aber ein Ei kann keine Attacken lernen.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Tut mir Leid…\p"
	.string "Es scheint, als hätte ich keine Attacke,\n"
	.string "die ich diesem Pokémon beibringen kann.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "Level-Up-Attacke$"

MoveRelearner_Text_EggMoveLWR::
	.string "Ei-attacke$"

MoveRelearner_Text_TMMoveLWR::
	.string "TM-attacke$"

MoveRelearner_Text_TutorMoveLWR::
	.string "Attacken-Lehrer$"

MoveRelearner_Text_MoveLWR::
	.string "Attacke$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Welche {STR_VAR_3} soll ich beibringen?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Danke, dass du unseren Service nutzt.\n"
	.string "Bitte komm bald wieder!$"
