gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to rest your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, ich nehme deine Pokémon\n"
	.string "für ein paar Sekunden.$"

gText_RestoredPkmnToFullHealth::
	.string "Deine Pokémon sind wieder topfit!$"

gText_WeHopeToSeeYouAgain::
	.string "Wir hoffen, dich bald wiederzusehen!$"

gText_WelcomeCutShort::
	.string "Hallo, Willkommen im\n"
	.string "Pokémon-Center.\p"
	.string "Möchtest du deine Pokémon\n"
	.string "heilen lassen?$"

gText_NoticesGoldCard::
	.string "Hallo, Trainer!\n"
	.string "Willkommen im Pokémon-Center!\p"
	.string "Wir heilen deine Pokémon und machen\n"
	.string "sie wieder fit.\p"
	.string "Sollen wir deine... D-dein Trainerpass!\n"
	.string "Diese intensive Farbe! Dieses Glitzern!\l"
	.string "Ich habe ja schon einige Trainer\n"
	.string "mit einem Silberpass getroffen,\l"
	.string "aber du stellst sie mit deinem Pass in\n"
	.string "dieser Farbe alle in den Schatten.\p"
	.string "{PLAYER}, erweist du mir die Ehre,\n"
	.string "dein Pokémon-Team heilen zu dürfen?$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, ich nehme deine Pokémon\n"
	.string "für ein paar Sekunden.$"

gText_ThankYouForWaiting::
	.string "Danke für deine Geduld.$"

gText_WeHopeToSeeYouAgain2::
	.string "Wir hoffen, dich bald wiederzusehen!$"
