gText_WouldYouLikeToRestYourPkmn::
	.string "Hallo, Willkommen im\n"
	.string "Pokémon-Center.\p"
	.string "Möchtest du deine Pokémon\n"
	.string "heilen lassen?$"

gText_IllTakeYourPkmn::
	.string "Okay, ich nehme deine Pokémon\n"
	.string "für ein paar Sekunden.$"

gText_RestoredPkmnToFullHealth::
	.string "Deine Pokémon sind wieder topfit!$"

gText_WeHopeToSeeYouAgain::
	.string "Wir hoffen, dich bald wiederzusehen!$"

gText_WelcomeCutShort::
	.string "Hallo, Willkommen im\n"
	.string "Pokémon-Center.\p"
	.string "Möchtest du deine Pokémon\n"
	.string "heilen lassen?$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "Hallo! Alles wie immer, {PLAYER}?$"

gText_IllTakeYourPkmn2::
	.string "Okay, ich nehme deine Pokémon\n"
	.string "für ein paar Sekunden.$"

gText_ThankYouForWaiting::
	.string "Danke für deine Geduld.$"

gText_WeHopeToSeeYouAgain2::
	.string "Wir hoffen, dich bald wiederzusehen!$"
