gText_WantToSurfWithPokemon:
    .string "Das Wasser ist ruhig…\n"
    .string "{STR_VAR_1} bitten zu surfen?$"

gText_MonHelpedSurf:
    .string "{STR_VAR_1} hilft dir gerne!$"

gText_WantToSurfWithItem:
    .string "Das Wasser ist ruhig…\n"
    .string "Das Multitool benutzen?$"

gText_PlayerUsedSurfItem:
    .string "Surfboard ausgepackt und\n"
    .string "es geht los!$"
    
gText_CantSurf:
    .string "Das Wasser ist ruhig… $"

@ will likely delete the below
gText_WantToUseSurf::
	.string "Das Wasser ist tiefblau.\n"
	.string "Möchtest du Surfer einsetzen?$"

gText_PlayerUsedSurf::
	.string "{STR_VAR_1} setzt Surfer ein.$"

Text_CurrentTooFast::
	.string "Die Strömung ist zu stark!\n"
	.string "Hier kann man nicht surfen…$"
