# 1 "data/maps/VerdanturfTown_House/scripts.pory"

# 2 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_MapScripts::
# 3 "data/maps/VerdanturfTown_House/scripts.pory"
	.byte 0
# 4 "data/maps/VerdanturfTown_House/scripts.pory"

# 5 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_EventScript_Woman1::
# 6 "data/maps/VerdanturfTown_House/scripts.pory"
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
# 7 "data/maps/VerdanturfTown_House/scripts.pory"
	end
# 8 "data/maps/VerdanturfTown_House/scripts.pory"

# 9 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_EventScript_Woman2::
# 10 "data/maps/VerdanturfTown_House/scripts.pory"
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
# 11 "data/maps/VerdanturfTown_House/scripts.pory"
	end
# 12 "data/maps/VerdanturfTown_House/scripts.pory"

# 13 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
# 14 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Weit von hier, in Prachtpolis City,\n"
# 15 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "findest du die Pokémon Liga.\p"
# 16 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Die Trainer dort sind alle geradezu\n"
# 17 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Furcht erregend talentiert.$"
# 18 "data/maps/VerdanturfTown_House/scripts.pory"

# 19 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_Text_DefeatEliteFourInARow:
# 20 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "In der Pokémon Liga musst du die Top\n"
# 21 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Vier hintereinander besiegen. Das\l"
# 22 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "sagen die Regeln.\p"
# 23 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Wenn du gegen einen dieser Trainer\n"
# 24 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "verlierst, musst du die Herausforderung\l"
# 25 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "von vorne beginnen.$"
