# 1 "data/maps/VictoryRoad_B1F/scripts.pory"

# 2 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_MapScripts::
# 3 "data/maps/VictoryRoad_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/VictoryRoad_B1F/scripts.pory"

# 5 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Samuel::
# 6 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_SAMUEL, VictoryRoad_B1F_Text_SamuelIntro, VictoryRoad_B1F_Text_SamuelDefeat
# 7 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_SamuelPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 9 "data/maps/VictoryRoad_B1F/scripts.pory"

# 10 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Shannon::
# 11 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_SHANNON, VictoryRoad_B1F_Text_ShannonIntro, VictoryRoad_B1F_Text_ShannonDefeat
# 12 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_ShannonPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 14 "data/maps/VictoryRoad_B1F/scripts.pory"

# 15 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Michelle::
# 16 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_MICHELLE, VictoryRoad_B1F_Text_MichelleIntro, VictoryRoad_B1F_Text_MichelleDefeat
# 17 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_MichellePostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 19 "data/maps/VictoryRoad_B1F/scripts.pory"

# 20 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Mitchell::
# 21 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_MITCHELL, VictoryRoad_B1F_Text_MitchellIntro, VictoryRoad_B1F_Text_MitchellDefeat
# 22 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_MitchellPostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 24 "data/maps/VictoryRoad_B1F/scripts.pory"

# 25 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Halle::
# 26 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_HALLE, VictoryRoad_B1F_Text_HalleIntro, VictoryRoad_B1F_Text_HalleDefeat
# 27 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_HallePostBattle, MSGBOX_AUTOCLOSE
# 28 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 29 "data/maps/VictoryRoad_B1F/scripts.pory"

# 30 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelIntro:
# 31 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Der Gedanke, dass ich der Pokémon Liga\n"
# 32 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "immer näher komme…\p"
# 33 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Ich bekomme Lampenfieber…$"
# 34 "data/maps/VictoryRoad_B1F/scripts.pory"

# 35 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelDefeat:
# 36 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Ich konnte gar nichts machen…$"
# 37 "data/maps/VictoryRoad_B1F/scripts.pory"

# 38 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelPostBattle:
# 39 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Die Pokémon Liga rückt in weite Ferne…\n"
# 40 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Was für eine Enttäuschung…$"
# 41 "data/maps/VictoryRoad_B1F/scripts.pory"

# 42 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonIntro:
# 43 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Um dich siegreich durch die Pokémon\n"
# 44 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Liga zu kämpfen, brauchst du das\l"
# 45 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Vertrauen deiner Pokémon.$"
# 46 "data/maps/VictoryRoad_B1F/scripts.pory"

# 47 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonDefeat:
# 48 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Eure Beziehung ist auf solidem\n"
# 49 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Vertrauen aufgebaut.$"
# 50 "data/maps/VictoryRoad_B1F/scripts.pory"

# 51 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonPostBattle:
# 52 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Das Vertrauen zwischen Pokémon und\n"
# 53 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Trainer wächst beständig, da sie immer\l"
# 54 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "zusammen sind.$"
# 55 "data/maps/VictoryRoad_B1F/scripts.pory"

# 56 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichelleIntro:
# 57 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Das ist nicht das Ziel. Nur eine\n"
# 58 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Zwischenstation auf dem Weg zur\l"
# 59 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Pokémon Liga.$"
# 60 "data/maps/VictoryRoad_B1F/scripts.pory"

# 61 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichelleDefeat:
# 62 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Das ist der Weg!$"
# 63 "data/maps/VictoryRoad_B1F/scripts.pory"

# 64 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichellePostBattle:
# 65 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Du wirst dich sehr gut schlagen, das ist\n"
# 66 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "sicher. Deine Pokémon lieben dich!$"
# 67 "data/maps/VictoryRoad_B1F/scripts.pory"

# 68 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellIntro:
# 69 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Meine Pokémon sind einfach kosmisch!\n"
# 70 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Beeindruckend und inspirierend.$"
# 71 "data/maps/VictoryRoad_B1F/scripts.pory"

# 72 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellDefeat:
# 73 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Jemanden wie dich habe ich noch nie\n"
# 74 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "getroffen.$"
# 75 "data/maps/VictoryRoad_B1F/scripts.pory"

# 76 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellPostBattle:
# 77 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Auch außerhalb eines Kampfes spüre\n"
# 78 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "ich die Kraft, die von dir und deinen\l"
# 79 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Pokémon ausgeht.$"
# 80 "data/maps/VictoryRoad_B1F/scripts.pory"

# 81 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HalleIntro:
# 82 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Du brauchst dich nicht gleich in Pose\n"
# 83 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "zu schmeißen! Bleib ganz ruhig.$"
# 84 "data/maps/VictoryRoad_B1F/scripts.pory"

# 85 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HalleDefeat:
# 86 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Whoa!\n"
# 87 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Wunderbar!$"
# 88 "data/maps/VictoryRoad_B1F/scripts.pory"

# 89 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HallePostBattle:
# 90 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Sicher, dies ist die Siegesstraße.\p"
# 91 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Aber sie unterscheidet sich nicht viel\n"
# 92 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "von dem Weg, den du bisher gegangen\l"
# 93 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "bist.\p"
# 94 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Versuch, den Rest des Weges zu\n"
# 95 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "genießen.$"
