# 1 "data/maps/SootopolisCity_House7/scripts.pory"

# 2 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_MapScripts::
# 3 "data/maps/SootopolisCity_House7/scripts.pory"
	.byte 0
# 4 "data/maps/SootopolisCity_House7/scripts.pory"

# 5 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_EventScript_OldMan::
# 6 "data/maps/SootopolisCity_House7/scripts.pory"
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
# 7 "data/maps/SootopolisCity_House7/scripts.pory"
	end
# 8 "data/maps/SootopolisCity_House7/scripts.pory"

# 9 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_EventScript_PokefanF::
# 10 "data/maps/SootopolisCity_House7/scripts.pory"
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
# 11 "data/maps/SootopolisCity_House7/scripts.pory"
	end
# 12 "data/maps/SootopolisCity_House7/scripts.pory"

# 13 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_Text_CityFromEruptedVolcano:
# 14 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "Ein Unterwasservulkan brach aus\n"
# 15 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "und schob sich an die Oberfläche.\p"
# 16 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "Der Krater lag über der Meeresober-\n"
# 17 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "fläche und konnte sich so mit Regen-\p"
# 18 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "wasser füllen.\n"
# 19 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "Und so entstand Xeneroville.$"
# 20 "data/maps/SootopolisCity_House7/scripts.pory"

# 21 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_Text_CaveMadeToKeepSomething:
# 22 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "Die Höhle, die Xeneroville mit der Welt\n"
# 23 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "verbindet…\p"
# 24 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "Sie sollte ursprünglich wohl etwas\n"
# 25 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "in der Stadt festhalten.\p"
# 26 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "Oder bilde ich mir das nur ein?$"
