# 1 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 2 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_MapScripts::
# 3 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.byte 0
# 4 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 5 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_EventScript_Shelly::
# 6 "data/maps/SeafloorCavern_Room3/scripts.pory"
	trainerbattle_single TRAINER_SHELLY_SEAFLOOR_CAVERN, SeafloorCavern_Room3_Text_ShellyIntro, SeafloorCavern_Room3_Text_ShellyDefeat
# 7 "data/maps/SeafloorCavern_Room3/scripts.pory"
	msgbox SeafloorCavern_Room3_Text_ShellyPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SeafloorCavern_Room3/scripts.pory"
	end
# 9 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 10 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_EventScript_Grunt5::
# 11 "data/maps/SeafloorCavern_Room3/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SEAFLOOR_CAVERN_5, SeafloorCavern_Room3_Text_Grunt5Intro, SeafloorCavern_Room3_Text_Grunt5Defeat
# 12 "data/maps/SeafloorCavern_Room3/scripts.pory"
	msgbox SeafloorCavern_Room3_Text_Grunt5PostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SeafloorCavern_Room3/scripts.pory"
	end
# 14 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 15 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_ShellyIntro:
# 16 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha!\p"
# 17 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Wie bist du uns ohne U-Boot gefolgt?\n"
# 18 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Was für ein bemerkenswertes Kind!\p"
# 19 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Aber… das berechtigt dich nicht, hier\n"
# 20 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "herumzuschnüffeln!\p"
# 21 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Jetzt kann ich dir die Sache vom\n"
# 22 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Klima-Institut heimzahlen…\p"
# 23 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ich gebe dir eine Lektion in Sachen\n"
# 24 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Schmerz! Pass gut auf!$"
# 25 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 26 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_ShellyDefeat:
# 27 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha!\p"
# 28 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Aua!$"
# 29 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 30 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_ShellyPostBattle:
# 31 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha!\n"
# 32 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Du bist unglaublich stark!\p"
# 33 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Es ist verdammt schade, dass du kein\n"
# 34 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Mitglied von Team Aqua bist!\p"
# 35 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "So könntest du an der wunderbaren,\n"
# 36 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "neuen Welt, die unser Boss seinen\l"
# 37 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Leuten versprochen hat, teilhaben…$"
# 38 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 39 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5Intro:
# 40 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Um unseren Traum Wirklichkeit werden\n"
# 41 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "zu lassen, brauchen wir die Kraft von\l"
# 42 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Pokémon.\p"
# 43 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Aber Nervensägen wie du nutzen die\n"
# 44 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Kraft der Pokémon, um selbst an Orten\l"
# 45 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "wie diesem allen auf den Keks zu gehen!\p"
# 46 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Das Leben funktioniert nicht so, wie wir\n"
# 47 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "uns das vorstellen.$"
# 48 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 49 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5Defeat:
# 50 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Gwah!$"
# 51 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 52 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5PostBattle:
# 53 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Weißt du, wir stellen die Motive\n"
# 54 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "unseres Anführers nie in Frage.\p"
# 55 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Und dann kommt ein Frettchen wie du\n"
# 56 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "dahergelaufen und legt sich\l"
# 57 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "mit unserem Boss an.\p"
# 58 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Vielleicht…\n"
# 59 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "bist du ja doch kein Frettchen…$"
