# 1 "data/maps/KantoArrival/scripts.pory"

# 2 "data/maps/KantoArrival/scripts.pory"
KantoArrival_MapScripts::
# 3 "data/maps/KantoArrival/scripts.pory"
	.byte 0
# 4 "data/maps/KantoArrival/scripts.pory"

# 5 "data/maps/KantoArrival/scripts.pory"
KantoArrival_EventScript_ArrivalText::
# 6 "data/maps/KantoArrival/scripts.pory"
	msgbox KantoArrival_Text_WelcomeToKanto, MSGBOX_SIGN
# 7 "data/maps/KantoArrival/scripts.pory"
	end
# 8 "data/maps/KantoArrival/scripts.pory"

# 9 "data/maps/KantoArrival/scripts.pory"
KantoArrival_Text_WelcomeToKanto::
# 10 "data/maps/KantoArrival/scripts.pory"
	.string "You arrived in Kanto!\n"
# 11 "data/maps/KantoArrival/scripts.pory"
	.string "Use the Fly Map to travel back to Hoenn.$"
