# 1 "data/maps/OldaleTown_House1/scripts.pory"

# 2 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_MapScripts::
# 3 "data/maps/OldaleTown_House1/scripts.pory"
	.byte 0
# 4 "data/maps/OldaleTown_House1/scripts.pory"

# 5 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_EventScript_Woman::
# 6 "data/maps/OldaleTown_House1/scripts.pory"
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
# 7 "data/maps/OldaleTown_House1/scripts.pory"
	end
# 8 "data/maps/OldaleTown_House1/scripts.pory"

# 9 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
# 10 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Das Pokémon auf der linken Seite der\n"
# 11 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Liste tritt im Kampf als Erstes an.\p"
# 12 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Hast du mehrere Pokémon in deinem Team,\n"
# 13 "data/maps/OldaleTown_House1/scripts.pory"
	.string "stelle sie so der Reihe nach auf, wie es\l"
# 14 "data/maps/OldaleTown_House1/scripts.pory"
	.string "für den Kampf am günstigsten ist.\p"
# 15 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Das kann ein Vorteil für dich sein.$"
