# 1 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 2 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_MapScripts::
# 3 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.byte 0
# 4 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 5 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_EventScript_Grunt15::
# 6 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_15, MagmaHideout_2F_2R_Text_Grunt15Intro, MagmaHideout_2F_2R_Text_Grunt15Defeat
# 7 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	msgbox MagmaHideout_2F_2R_Text_Grunt15PostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	end
# 9 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 10 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_EventScript_Grunt6::
# 11 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_6, MagmaHideout_2F_2R_Text_Grunt6Intro, MagmaHideout_2F_2R_Text_Grunt6Defeat
# 12 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	msgbox MagmaHideout_2F_2R_Text_Grunt6PostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	end
# 14 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 15 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_EventScript_Grunt7::
# 16 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_7, MagmaHideout_2F_2R_Text_Grunt7Intro, MagmaHideout_2F_2R_Text_Grunt7Defeat
# 17 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	msgbox MagmaHideout_2F_2R_Text_Grunt7PostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	end
# 19 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 20 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_EventScript_Grunt8::
# 21 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_8, MagmaHideout_2F_2R_Text_Grunt8Intro, MagmaHideout_2F_2R_Text_Grunt8Defeat
# 22 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	msgbox MagmaHideout_2F_2R_Text_Grunt8PostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	end
# 24 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 25 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt15Intro:
# 26 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Ich habe nichts gegen dich!\n"
# 27 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Aber ich habe meine Befehle.$"
# 28 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 29 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt15Defeat:
# 30 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Ich mag vielleicht verloren haben,\n"
# 31 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "aber…$"
# 32 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 33 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt15PostBattle:
# 34 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Wir haben etwas Unglaubliches\n"
# 35 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "ausgegraben! Und… wir haben die Blaue\l"
# 36 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Kugel!\p"
# 37 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Nun muss unser Boss nur noch…\n"
# 38 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Hahaha… Muahahahahahaha!$"
# 39 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 40 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt6Intro:
# 41 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Ich hasse Hitze! Ich hätte mich lieber\n"
# 42 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Team Aqua anschließen sollen…$"
# 43 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 44 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt6Defeat:
# 45 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Ich bin tatsächlich nicht geschaffen\n"
# 46 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "für Team Magma…$"
# 47 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 48 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt6PostBattle:
# 49 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Bekommst du an einem Ort wie diesem\n"
# 50 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "nicht Sehnsucht nach dem Meer?$"
# 51 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 52 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt7Intro:
# 53 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Ab und zu bemerkt man hier\n"
# 54 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Erschütterungen.\p"
# 55 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Ob der Vulkan daran schuld ist?\n"
# 56 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Oder ist es Grou…\p"
# 57 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Huuups!\n"
# 58 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Ach, egal! Dummdidumm…$"
# 59 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 60 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt7Defeat:
# 61 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Du bist ein hitziger Kämpfer.\n"
# 62 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Wie ein Vulkan.$"
# 63 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 64 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt7PostBattle:
# 65 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Dieses Mal hast du es tatsächlich\n"
# 66 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "geschafft, zu gewinnen. Aber das macht\l"
# 67 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "überhaupt nichts.\p"
# 68 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Team Magma ist bald am Ziel.$"
# 69 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 70 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt8Intro:
# 71 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Eines unserer Mitglieder ist aus-\n"
# 72 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "gerastet. Es hat sein Magmaemblem\l"
# 73 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "verloren!\p"
# 74 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Warte mal! Du hast das doch nicht\n"
# 75 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "etwa gefunden?!?$"
# 76 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 77 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt8Defeat:
# 78 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Das kann ich einfach nicht glauben…$"
# 79 "data/maps/MagmaHideout_2F_2R/scripts.pory"

# 80 "data/maps/MagmaHideout_2F_2R/scripts.pory"
MagmaHideout_2F_2R_Text_Grunt8PostBattle:
# 81 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Ich habe das Gefühl, dass unser Plan\n"
# 82 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "scheitern wird…$"
