@ Flavor text for interacting with various background objects

EventScript_Bookshelf::
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf::
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food::
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame::
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer::
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine::
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints::
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary::
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen::
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet::
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen::
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser::
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks::
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting::
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine::
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone::
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster::
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood::
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin::
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup::
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow::
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow::
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights::
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools::
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign::
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign::
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal::
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority::
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end

@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Ein Poster von einem Pokémon.\n"
	.string "Das Pokémon springt heraus.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "Ein Stadtplan.$"

Text_PokeMartShelf::
	.string "Ein Bild von zwei Pokémon,\n"
	.string "die sich lieben.$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Ein Pokémon treibt auf dem\n"
	.string "Rücken im Wasser.$"

Text_Kitchen::
	.string "Ein Gemälde eines\n"
	.string "schönen Wasserfalls.$"

Text_Dresser::
	.string "Es ist ein Pokémon.\n"
	.string "Bewegt sich aber gar nicht.$"

Text_Snacks::
	.string "Ein Berg von Schuhen!$"

Text_PokemartSign::
	.string "Ein Bild einer verschneiten\n"
	.string "Landschaft.$"

Text_PokecenterSign::
	.string "Das Angel-Pokémon sieht\n"
	.string "glücklich aus.$"

Text_Indigo_UltimateGoal::
	.string "Indigo-Plateau\p"
	.string "Das ultimative Ziel aller Trainer!\n"
	.string "Hauptquartier der Pokémon Liga.$"

Text_Indigo_HighestAuthority::
	.string "Indigo-Plateau\p"
	.string "Das Pokémon Liga-Hauptquartier ist\n"
	.string "die höchste Pokémon-Autorität!$"

Text_Food::
	.string "Es ist ein Pokémon.\n"
	.string "Es scheint zu schlafen.$"

Text_Blueprints::
	.string "Irgendein Bauplan.\n"
	.string "Voller Diagramme und Text.$"

Text_Painting::
	.string "Ein Gruppenfoto von\n"
	.string "Pokémon-Trainern.$"

Text_PowerPlantMachine::
	.string "Irgendeine Maschine.$"

Text_Telephone::
	.string "Ein kleiner Safe.$"

Text_Computer::
	.string "Ein Riesenballon in Pokémonform!\n"
	.string "Ein Pokémonballon.$"

Text_AdvertisingPoster::
	.string "Ein Werbeplakat für\n"
	.string "allerlei Produkte.$"

Text_TastyFood::
	.string "Ein Pokémon entspannt\n"
	.string "sich am Fenster.$"

Text_TrashBin::
	.string "Ein Pokémon ist im Käfig.$"

Text_Cup::
	.string "Ein Pokémon döst\n"
	.string "gemütlich vor sich hin.$"

Text_PolishedWindow::
	.string "Eine glänzende, neue Maschine.$"

Text_BeautifulSkyWindow::
	.string "Draußen vor dem Fenster...\n"
	.string "Der Himmel sieht fantastisch\n"
	.string "schön aus.$"

Text_BlinkingLights::
	.string "Lichter in verschiedenen Farben\n"
	.string "blinken auf und ab.$"

Text_NeatlyLinedUpTools::
	.string "Eine hübsche Blumenvase.$"

Text_ImpressiveMachine::
	.string "Ein Gemälde einer prächtigen\n"
	.string "Landschaft.$"

Text_VideoGame::
	.string "Ein Plakat für einen\n"
	.string "Pokémon-Wettbewerb.$"

Text_Burglary::
	.string "Eine große Anzahl Pokémon\n"
	.string "wuselt überall herum.$"

Text_PlayerFacingTVScreen::
	.string "Ein wirklich\n"
	.string "großer Fisch!$"
