gText_HowMayIServeYou::
	.string "Willkommen!\p"
	.string "Kann ich dir helfen?$"

gText_PleaseComeAgain::
	.string "Bitte komm bald wieder!$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{STRING 5}, willkommen!\p"
	.string "Wie kann ich dir behilflich sein?$"

Pokemart_DefaultItemList::
	.2byte ITEM_ULTRA_BALL
	.2byte ITEM_HYPER_POTION
	.2byte ITEM_MAX_POTION
	.2byte ITEM_FULL_RESTORE
	.2byte ITEM_FULL_HEAL
	.2byte ITEM_REVIVE
	.2byte ITEM_MAX_REPEL
	pokemartlistend
