# 1 "data/maps/OldaleTown_House2/scripts.pory"

# 2 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_MapScripts::
# 3 "data/maps/OldaleTown_House2/scripts.pory"
	.byte 0
# 4 "data/maps/OldaleTown_House2/scripts.pory"

# 5 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_EventScript_Woman::
# 6 "data/maps/OldaleTown_House2/scripts.pory"
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
# 7 "data/maps/OldaleTown_House2/scripts.pory"
	end
# 8 "data/maps/OldaleTown_House2/scripts.pory"

# 9 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_EventScript_Man::
# 10 "data/maps/OldaleTown_House2/scripts.pory"
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
# 11 "data/maps/OldaleTown_House2/scripts.pory"
	end
# 12 "data/maps/OldaleTown_House2/scripts.pory"

# 13 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_Text_PokemonLevelUp:
# 14 "data/maps/OldaleTown_House2/scripts.pory"
	.string "Während eines Kampfes können Pokémon\n"
# 15 "data/maps/OldaleTown_House2/scripts.pory"
	.string "manchmal einen Level dazugewinnen und\l"
# 16 "data/maps/OldaleTown_House2/scripts.pory"
	.string "stärker werden.$"
# 17 "data/maps/OldaleTown_House2/scripts.pory"

# 18 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon:
# 19 "data/maps/OldaleTown_House2/scripts.pory"
	.string "Sobald deine Team-Pokémon stärker\n"
# 20 "data/maps/OldaleTown_House2/scripts.pory"
	.string "geworden sind, kannst du auch andere\l"
# 21 "data/maps/OldaleTown_House2/scripts.pory"
	.string "Orte bereisen.$"
