# 1 "data/maps/SlateportCity_House/scripts.pory"

# 2 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_MapScripts::
# 3 "data/maps/SlateportCity_House/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_House/scripts.pory"

# 5 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_PokefanM::
# 6 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
# 7 "data/maps/SlateportCity_House/scripts.pory"
	end
# 8 "data/maps/SlateportCity_House/scripts.pory"

# 9 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_Girl::
# 10 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
# 11 "data/maps/SlateportCity_House/scripts.pory"
	end
# 12 "data/maps/SlateportCity_House/scripts.pory"

# 13 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_NatureToDoWithStatGains:
# 14 "data/maps/SlateportCity_House/scripts.pory"
	.string "Mein Pokémon hat ein hastiges Wesen.\p"
# 15 "data/maps/SlateportCity_House/scripts.pory"
	.string "Seine Initiative ist im Vergleich\n"
# 16 "data/maps/SlateportCity_House/scripts.pory"
	.string "zu meinen anderen Pokémon höher.\p"
# 17 "data/maps/SlateportCity_House/scripts.pory"
	.string "Vielleicht hat ihr Wesen etwas mit den\n"
# 18 "data/maps/SlateportCity_House/scripts.pory"
	.string "Statusvorteilen der Pokémon zu tun.$"
# 19 "data/maps/SlateportCity_House/scripts.pory"

# 20 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_MustBeGoingToBattleTent:
# 21 "data/maps/SlateportCity_House/scripts.pory"
	.string "Du bist doch ein Trainer, oder?\p"
# 22 "data/maps/SlateportCity_House/scripts.pory"
	.string "Da du schon mal in Graphitport City\n"
# 23 "data/maps/SlateportCity_House/scripts.pory"
	.string "bist, besuch unbedingt das Kampfcamp!$"
