# 1 "data/maps/PetalburgCity_House1/scripts.pory"

# 2 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_MapScripts::
# 3 "data/maps/PetalburgCity_House1/scripts.pory"
	.byte 0
# 4 "data/maps/PetalburgCity_House1/scripts.pory"

# 5 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_EventScript_Man::
# 6 "data/maps/PetalburgCity_House1/scripts.pory"
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
# 7 "data/maps/PetalburgCity_House1/scripts.pory"
	end
# 8 "data/maps/PetalburgCity_House1/scripts.pory"

# 9 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_EventScript_Woman::
# 10 "data/maps/PetalburgCity_House1/scripts.pory"
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
# 11 "data/maps/PetalburgCity_House1/scripts.pory"
	end
# 12 "data/maps/PetalburgCity_House1/scripts.pory"

# 13 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_Text_TravelingIsWonderful:
# 14 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Reisen ist einfach wundervoll!\p"
# 15 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Als ich noch jung war, waren die See und\n"
# 16 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "die Berge mein Zuhause.$"
# 17 "data/maps/PetalburgCity_House1/scripts.pory"

# 18 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_Text_GoOnAdventure:
# 19 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Seufz…\p"
# 20 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Ich wünschte, ich könnte mit einigen\n"
# 21 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Pokémon auf Abenteuerreise gehen…\p"
# 22 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Sich durch hohes Gras schleichen…\n"
# 23 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Steile, zerklüftete Berge erklimmen…\p"
# 24 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Das tosende Meer überqueren…\n"
# 25 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Dunkle Höhlen erforschen…\p"
# 26 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Und manchmal ein wenig Heimweh haben…\p"
# 27 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Reisen muss einfach toll sein!$"
