# 1 "data/maps/FortreeCity_House3/scripts.pory"

# 2 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_MapScripts::
# 3 "data/maps/FortreeCity_House3/scripts.pory"
	.byte 0
# 4 "data/maps/FortreeCity_House3/scripts.pory"

# 5 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_EventScript_Maniac::
# 6 "data/maps/FortreeCity_House3/scripts.pory"
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
# 7 "data/maps/FortreeCity_House3/scripts.pory"
	end
# 8 "data/maps/FortreeCity_House3/scripts.pory"

# 9 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_EventScript_SchoolKidM::
# 10 "data/maps/FortreeCity_House3/scripts.pory"
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
# 11 "data/maps/FortreeCity_House3/scripts.pory"
	end
# 12 "data/maps/FortreeCity_House3/scripts.pory"

# 13 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
# 14 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Da wir gerade vom Pokédex reden… Ich\n"
# 15 "data/maps/FortreeCity_House3/scripts.pory"
	.string "erinnere mich…\p"
# 16 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Ich habe diesen Trainer, Troy,\n"
# 17 "data/maps/FortreeCity_House3/scripts.pory"
	.string "getroffen, als ich seltene Steine\l"
# 18 "data/maps/FortreeCity_House3/scripts.pory"
	.string "suchte.\p"
# 19 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Oh Junge, der hatte vielleicht\n"
# 20 "data/maps/FortreeCity_House3/scripts.pory"
	.string "interessante Pokémon bei sich!\p"
# 21 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Die waren nicht nur selten, sondern\n"
# 22 "data/maps/FortreeCity_House3/scripts.pory"
	.string "auch ausgesprochen gut trainiert!\p"
# 23 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Er ist bestimmt stärker als die Arena-\n"
# 24 "data/maps/FortreeCity_House3/scripts.pory"
	.string "leiterin in diesem Ort…$"
# 25 "data/maps/FortreeCity_House3/scripts.pory"

# 26 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_Text_OhYouHavePokedex:
# 27 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Was ist das da? Was hast du da?\p"
# 28 "data/maps/FortreeCity_House3/scripts.pory"
	.string "… … … … … …\p"
# 29 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Oh, das ist also ein Pokédex?\n"
# 30 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Der ist aber wirklich klasse!$"
