# 1 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 2 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_MapScripts::
# 3 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 5 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Andrea::
# 6 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
# 7 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 9 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 10 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Crissy::
# 11 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
# 12 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 14 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 15 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Brianna::
# 16 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
# 17 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 19 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 20 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Connie::
# 21 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
# 22 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 24 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 25 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Bridget::
# 26 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
# 27 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
# 28 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 29 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 30 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Olivia::
# 31 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
# 32 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
# 33 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 34 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 35 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Tiffany::
# 36 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
# 37 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
# 38 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 39 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 40 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Bethany::
# 41 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
# 42 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
# 43 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 44 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 45 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Annika::
# 46 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
# 47 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
# 48 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 49 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 50 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Daphne::
# 51 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
# 52 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
# 53 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 54 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 55 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaIntro:
# 56 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich zeige dir die vollendeten,\n"
# 57 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Techniken die ich von Juan\l"
# 58 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "gelernt habe.$"
# 59 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 60 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaDefeat:
# 61 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Bitte verzeih mir, Juan…$"
# 62 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 63 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
# 64 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Pass auf, was passiert, wenn du alle\n"
# 65 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Bodenfliesen betreten hast…$"
# 66 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 67 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyIntro:
# 68 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Du bist den ganzen Weg hierher ge-\n"
# 69 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "kommen, aber bis zu Juan dringst\l"
# 70 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "du nicht vor.\p"
# 71 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Weil du gegen mich verlieren wirst!$"
# 72 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 73 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyDefeat:
# 74 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Du bist stark! Ich habe mich durch dein\n"
# 75 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "unschuldiges Aussehen täuschen\l"
# 76 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "lassen.$"
# 77 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 78 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
# 79 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Du bist gut genug, um nicht sofort von\n"
# 80 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Juan besiegt zu werden.$"
# 81 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 82 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphneIntro:
# 83 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Die Art, wie Juan kämpft…\p"
# 84 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Dieser wunderbare Anblick hat mich dazu\n"
# 85 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "inspiriert, Trainer zu werden.$"
# 86 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 87 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphneDefeat:
# 88 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Du kämpfst mit mehr Anmut als ich…$"
# 89 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 90 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
# 91 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Die Ästhetik, die du in den Kampf ein-\n"
# 92 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "bringst, ist unbeschreiblich.\p"
# 93 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh… Ich bin so glücklich, dass ich mich\n"
# 94 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "für Pokémon entschieden habe.$"
# 95 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 96 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConnieIntro:
# 97 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich werde dir beibringen, dass Kämpfe\n"
# 98 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "kein Zuckerschlecken sind!$"
# 99 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 100 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConnieDefeat:
# 101 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh.\n"
# 102 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Du bist stark.$"
# 103 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 104 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConniePostBattle:
# 105 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich verrate dir etwas.\p"
# 106 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Wenn du zu Juan willst, dann darfst\n"
# 107 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "du auf jede Fliese nur ein Mal treten.$"
# 108 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 109 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetIntro:
# 110 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Die Pokémon Arena mit den höchsten\n"
# 111 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Anforderungen in der Hoenn-Region…\p"
# 112 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Das ist die Arena von Xeneroville.$"
# 113 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 114 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetDefeat:
# 115 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Du kämpfst aber auf einem hohen\n"
# 116 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Niveau!$"
# 117 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 118 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
# 119 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Statt damit zufrieden zu sein, zur\n"
# 120 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "besten Arena zu gehören, würde ich\l"
# 121 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "gerne auch an anderen Orten trainieren.\l"
# 122 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Aber hier ist es so lustig!$"
# 123 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 124 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaIntro:
# 125 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich trainiere meine Pokémon zusammen\n"
# 126 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "mit Juan.\p"
# 127 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich bin nicht leicht zu besiegen!$"
# 128 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 129 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaDefeat:
# 130 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Da wurde ich besiegt…$"
# 131 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 132 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
# 133 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich denke, du hast durchaus Potenzial.\n"
# 134 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Warum bleibst du nicht bei uns?$"
# 135 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 136 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyIntro:
# 137 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Anmutig über das Eis zu gleiten, ohne\n"
# 138 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "die Linien zu berühren…\p"
# 139 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ein Trainer, der das beherrscht, wird\n"
# 140 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "auch in anderen Dingen elegant wirken.$"
# 141 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 142 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
# 143 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Äh, entschuldige mich…$"
# 144 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 145 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
# 146 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Es ist offensichtlich: Die Stärke eines\n"
# 147 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Trainers hat nichts mit seinem Alter\l"
# 148 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "zu tun!$"
# 149 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 150 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyIntro:
# 151 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Wenn ich mit meinen Pokémon zusammen\n"
# 152 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "bin, vergeht die Zeit so schnell, dass\l"
# 153 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "ich noch nicht mal “Uuups” sagen kann.$"
# 154 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 155 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyDefeat:
# 156 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Uuups!$"
# 157 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 158 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
# 159 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich wollte, ich könnte meine\n"
# 160 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Niederlage vergessen, bevor ich\l"
# 161 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "“Uuups” ausgesprochen habe.$"
# 162 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 163 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaIntro:
# 164 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Wenn du magst, setze ich im Kampf viele\n"
# 165 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "seltene Pokémon ein.$"
# 166 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 167 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
# 168 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Und? Hast du dir meine Pokémon\n"
# 169 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "gut angesehen?$"
# 170 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 171 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
# 172 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich bin zu dieser Arena gekommen, weil\n"
# 173 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Juan meine geliebten Pokémon gelobt\l"
# 174 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "hat.\p"
# 175 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Wäre ich Juan nur früher begegnet, als\n"
# 176 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "ich noch jung war…$"
# 177 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 178 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaIntro:
# 179 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Kicher…\n"
# 180 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Dein grimmiger Ausdruck ist total\l"
# 181 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "niedlich.$"
# 182 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 183 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaDefeat:
# 184 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh je.\n"
# 185 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ich habe es dir viel zu leicht gemacht.$"
# 186 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 187 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
# 188 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Du kannst Juan kein Härchen krümmen,\n"
# 189 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "wetten? Kicher…$"
