# 1 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 2 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_MapScripts::
# 3 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.byte 0
# 4 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 5 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_EventScript_Grunt9::
# 6 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_9, MagmaHideout_3F_1R_Text_Grunt9Intro, MagmaHideout_3F_1R_Text_Grunt9Defeat
# 7 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	msgbox MagmaHideout_3F_1R_Text_Grunt9PostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	end
# 9 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 10 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_EventScript_Grunt16::
# 11 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_16, MagmaHideout_3F_1R_Text_Grunt16Intro, MagmaHideout_3F_1R_Text_Grunt16Defeat
# 12 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	msgbox MagmaHideout_3F_1R_Text_Grunt16PostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	end
# 14 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 15 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt9Intro:
# 16 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Was habe ich nur getan, dass ich hier\n"
# 17 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Wache schieben muss?\p"
# 18 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Mein linkes Ohr brennt schon wie\n"
# 19 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "verrückt.$"
# 20 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 21 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt9Defeat:
# 22 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Ich bekomme gleich einen Hitzschlag…$"
# 23 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 24 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt9PostBattle:
# 25 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Findest du es merkwürdig, dass wir auf\n"
# 26 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "diesem Vulkan auch noch Hüte tragen?$"
# 27 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 28 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt16Intro:
# 29 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Wir haben uns zusammengeschlossen,\n"
# 30 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "damit seine fantastische Vision\l"
# 31 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Wirklichkeit wird.\p"
# 32 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Es ist mir schnurzegal, ob du zu Team\n"
# 33 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Aqua gehörst oder einfach nur ein Kind\l"
# 34 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "bist, das hier vorbeikommt.\p"
# 35 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Niemand mischt sich in unsere Belange\n"
# 36 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "ein und kommt ungeschoren davon!$"
# 37 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 38 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt16Defeat:
# 39 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Oh, nein!\n"
# 40 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Dich habe ich ganz falsch eingeschätzt.$"
# 41 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 42 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt16PostBattle:
# 43 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Hör zu!\n"
# 44 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Team Magma hat Recht!\p"
# 45 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Hör nicht auf Team Aqua!\n"
# 46 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Glaub ihren Lügen nicht.$"
