# 1 "data/maps/LilycoveCity_House4/scripts.pory"

# 2 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_MapScripts::
# 3 "data/maps/LilycoveCity_House4/scripts.pory"
	.byte 0
# 4 "data/maps/LilycoveCity_House4/scripts.pory"

# 5 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_EventScript_Man1::
# 6 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
# 7 "data/maps/LilycoveCity_House4/scripts.pory"
	end
# 8 "data/maps/LilycoveCity_House4/scripts.pory"

# 9 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_EventScript_Man2::
# 10 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
# 11 "data/maps/LilycoveCity_House4/scripts.pory"
	end
# 12 "data/maps/LilycoveCity_House4/scripts.pory"

# 13 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
# 14 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Das größte Geheimnis dieses Planeten\n"
# 15 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "hütet der Meeresboden.\p"
# 16 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Das hat mal jemand gesagt, aber ich\n"
# 17 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "weiß nicht…$"
# 18 "data/maps/LilycoveCity_House4/scripts.pory"

# 19 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
# 20 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Zwischen Moosbach City und\n"
# 21 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Xeneroville befindet sich ein\l"
# 22 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "tiefer Unterwassergraben.\p"
# 23 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Das hat mir jemand erzählt.$"
